/**
 * link-inbox: wire the in-box DSH packages this repo consumes at runtime to
 * a local DSH checkout. Two jobs:
 *
 * 1. Dev stub for `@deepseek-ai/dsh-tools` (NOT published installably — its
 *    transitive deps are unpublished): minimal TYPES in the package's
 *    node_modules (so the typert analyzer sees no checkout files) plus a
 *    runtime re-export of the checkout's real implementation. The stub dir
 *    lives under node_modules and is gitignored by construction.
 * 2. Dev junction of `@deepseek-ai/dsh-typert-generator` (the npm release is
 *    internally inconsistent: rc.1 generator vs rc.6 protocol): replaces the
 *    registry-installed copy with a junction to the checkout's built
 *    generator, which matches the vendored protocol.
 *
 * Usage: node scripts/link-inbox.mjs <path-to-dsh-checkout>
 */

import { existsSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const pkg = join(root, 'packages', 'dsh-config-migrator')

const checkout = resolve(process.argv[2] ?? '')
if (checkout === '' || !existsSync(join(checkout, 'package.json'))) {
  console.error('usage: node scripts/link-inbox.mjs <path-to-dsh-checkout>')
  process.exit(1)
}
const toolsLib = join(checkout, 'packages', 'core', 'tools', 'lib', 'index.js')
if (!existsSync(toolsLib)) {
  console.error(`link-inbox: ${toolsLib} not found — build the DSH checkout first (or check the path)`)
  process.exit(1)
}

// 1. dsh-tools dev stub.
const stub = join(pkg, 'node_modules', '@deepseek-ai', 'dsh-tools')
rmSync(stub, { recursive: true, force: true })
mkdirSync(stub, { recursive: true })
writeFileSync(join(stub, 'package.json'), JSON.stringify({
  name: '@deepseek-ai/dsh-tools',
  version: '0.0.0-dev',
  description: 'Dev stub: minimal types for the in-box dsh-tools; runtime re-exports the local DSH checkout (generated by scripts/link-inbox.mjs — never published)',
  type: 'module',
  types: './index.d.ts',
  main: './index.js',
}, undefined, 2) + '\n')
writeFileSync(join(stub, 'index.d.ts'), [
  '/** Dev stub types for the in-box `@deepseek-ai/dsh-tools` (see package.json). */',
  'export function defineTool(definition: {',
  '  name: string',
  '  description: string',
  '  parameters: Record<string, unknown>',
  '  output?: unknown',
  '  timeoutMs?: number',
  '  execute: (args: Record<string, any>, exec?: unknown) => string | Promise<string>',
  '}): unknown',
  '',
].join('\n'))
writeFileSync(join(stub, 'index.js'), [
  '// Dev stub runtime: re-export the real in-box dsh-tools from the local DSH checkout.',
  `export * from ${JSON.stringify(pathToFileURL(toolsLib).href)}`,
  '',
].join('\n'))
console.log(`dsh-tools stub -> ${toolsLib}`)

// 2. typert generator junction over the registry copy.
const genDir = join(pkg, 'node_modules', '@deepseek-ai', 'dsh-typert-generator')
const genTarget = join(checkout, 'packages', 'typert', 'generator')
if (existsSync(join(genTarget, 'lib', 'types', 'tsdown-plugin.js'))) {
  rmSync(genDir, { recursive: true, force: true })
  mkdirSync(dirname(genDir), { recursive: true })
  symlinkSync(genTarget, genDir, process.platform === 'win32' ? 'junction' : 'dir')
  console.log(`typert generator junction -> ${genTarget}`)
} else {
  console.log(`link-inbox: ${genTarget} not built — skipping the generator junction (Remote artifacts need it)`)
}
