/**
 * link-inbox: wire the in-box DSH packages this repo consumes at runtime to
 * a local DSH checkout. Two jobs:
 *
 * 1. Dev stub for `@deepseek-ai/dsh-tools` (NOT published installably — its
 *    transitive deps are unpublished): minimal TYPES in the package's
 *    node_modules (so the typert analyzer sees no checkout files) plus a
 *    runtime re-export of the checkout's real implementation. The stub dir
 *    lives under node_modules and is gitignored by construction.
 * 2. Dev junction of `@deepseek-ai/dsh-typert-generator` (the npm release is
 *    internally inconsistent: rc.1 generator vs rc.6 protocol): replaces the
 *    registry-installed copy with a junction to the checkout's built
 *    generator, which matches the vendored protocol.
 *
 * Usage: node scripts/link-inbox.mjs <path-to-dsh-checkout>
 */

import { existsSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const pkg = join(root, 'packages', 'dsh-config-migrator')

const checkout = resolve(process.argv[2] ?? '')
if (checkout === '' || !existsSync(join(checkout, 'package.json'))) {
  console.error('usage: node scripts/link-inbox.mjs <path-to-dsh-checkout>')
  process.exit(1)
}
const toolsLib = join(checkout, 'packages', 'core', 'tools', 'lib', 'index.js')
if (!existsSync(toolsLib)) {
  console.error(`link-inbox: ${toolsLib} not found — build the DSH checkout first (or check the path)`)
  process.exit(1)
}

// 1. dsh-tools dev stub.
const stub = join(pkg, 'node_modules', '@deepseek-ai', 'dsh-tools')
rmSync(stub, { recursive: true, force: true })
mkdirSync(stub, { recursive: true })
writeFileSync(join(stub, 'package.json'), JSON.stringify({
  name: '@deepseek-ai/dsh-tools',
  version: '0.0.0-dev',
  description: 'Dev stub: minimal types for the in-box dsh-tools; runtime re-exports the local DSH checkout (generated by scripts/link-inbox.mjs — never published)',
  type: 'module',
  types: './index.d.ts',
  main: './index.js',
}, undefined, 2) + '\n')
writeFileSync(join(stub, 'index.d.ts'), [
  '/** Dev stub types for the in-box `@deepseek-ai/dsh-tools` (see package.json). */',
  'export function defineTool(definition: {',
  '  name: string',
  '  description: string',
  '  parameters: Record<string, unknown>',
  '  output?: unknown',
  '  timeoutMs?: number',
  '  execute: (args: Record<string, any>, exec?: unknown) => string | Promise<string>',
  '}): unknown',
  '',
].join('\n'))
writeFileSync(join(stub, 'index.js'), [
  '// Dev stub runtime: re-export the real in-box dsh-tools from the local DSH checkout.',
  `export * from ${JSON.stringify(pathToFileURL(toolsLib).href)}`,
  '',
].join('\n'))
console.log(`dsh-tools stub -> ${toolsLib}`)

// 2. Vendored checkout generator: the npm release is internally inconsistent
//    (rc.1 generator vs rc.6 protocol), so the build imports the checkout's
//    generator from scripts/vendor-typert2 (tsdown.config.ts resolves it by
//    relative path). Copy its built lib and junction the checkout's
//    node_modules so its own deps (typescript, zod, @jridgewell/*) resolve.
const vendorDir = join(root, 'scripts', 'vendor-typert2')
const genLib = join(checkout, 'packages', 'typert', 'generator', 'lib')
if (existsSync(join(genLib, 'types', 'tsdown-plugin.js'))) {
  rmSync(vendorDir, { recursive: true, force: true })
  mkdirSync(vendorDir, { recursive: true })
  const { cpSync } = await import('node:fs')
  cpSync(genLib, vendorDir, { recursive: true })
  mkdirSync(join(vendorDir, 'node_modules'), { recursive: true })
  symlinkSync(join(checkout, 'node_modules'), join(vendorDir, 'node_modules', 'checkout-store'), process.platform === 'win32' ? 'junction' : 'dir')
  console.log(`vendored typert generator -> ${vendorDir}`)
} else {
  console.log(`link-inbox: ${genLib} not built — skipping generator vendoring (Remote artifacts need it)`)
}

// 3. Client dev types: the published client rc packages typecheck against a
//    locale/slot map that predates third-party namespaces, and the registry
//    has been flaky for their deep graphs — junction the checkout packages
//    (types match the module table exactly; never bundled).
const nm = join(pkg, 'node_modules')
const clientLinks = {
  '@deepseek-ai/dsh-client-runtime': 'packages/client/runtime',
  '@deepseek-ai/dsh-client-ui-settings': 'packages/client/ui-settings',
  '@deepseek-ai/dsh-client-ui-slots': 'packages/client/ui-slots',
  '@deepseek-ai/dsh-client-locale': 'packages/client/locale',
  '@deepseek-ai/dsh-client-connection': 'packages/client/connection',
  '@deepseek-ai/dsh-api-remotes': 'packages/api/remotes',
}
for (const [name, relative] of Object.entries(clientLinks)) {
  const source = join(checkout, relative)
  if (!existsSync(join(source, 'package.json'))) continue
  const dest = join(nm, ...name.split('/'))
  rmSync(dest, { recursive: true, force: true })
  mkdirSync(dirname(dest), { recursive: true })
  symlinkSync(source, dest, process.platform === 'win32' ? 'junction' : 'dir')
  console.log(`client dev link ${name} -> ${source}`)
}
// react + types from the checkout's pnpm store (not hoisted at the root).
for (const [storePattern, name] of [
  ['react@18*', 'react'],
  ['@types+react@18*', '@types/react'],
]) {
  const store = join(checkout, 'node_modules', '.pnpm')
  const match = readdirSync(store).find(entry => {
    const base = entry.split('+', 2).join('+')
    return base === storePattern.replace('*', '') || (storePattern.endsWith('*') && entry.startsWith(storePattern.slice(0, -1)))
  })
  if (match === undefined) continue
  const source = join(store, match, 'node_modules', ...name.split('/'))
  if (!existsSync(source)) continue
  const dest = join(nm, ...name.split('/'))
  rmSync(dest, { recursive: true, force: true })
  mkdirSync(dirname(dest), { recursive: true })
  symlinkSync(source, dest, process.platform === 'win32' ? 'junction' : 'dir')
  console.log(`store link ${name} -> ${source}`)
}
